/* Common parser/lexer shared declarations to avoid circular include issues.
 * This header provides a stable definition of YYLTYPE and prototypes for
 * the reentrant scanner so both the generated lexer and parser see the
 * same declarations.
 */
#pragma once

#include "sql/parser/parse_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Location type used by Bison/Flex. Define only if not already declared by
 * a generated bison header. We also define YYLTYPE_IS_DECLARED so bison's
 * generated header will skip redefining it. */
#ifndef YYLTYPE_IS_DECLARED
typedef struct YYLTYPE {
  int first_line;
  int first_column;
  int last_line;
  int last_column;
} YYLTYPE;
#define YYLTYPE_IS_DECLARED 1
#endif

/* Forward-declare YYSTYPE as an incomplete type; the real union is
 * generated by Bison. We only need pointer references here. */
union YYSTYPE; typedef union YYSTYPE YYSTYPE;

/* Reentrant scanner handle */
typedef void *yyscan_t;

/* Prototypes for scanner helpers (implemented in flex output) */
extern int yylex(YYSTYPE * yylval_param, YYLTYPE * yylloc_param, yyscan_t yyscanner);
int yylex_init_extra(void *user_defined, yyscan_t *scanner);
int yylex_destroy(yyscan_t scanner);
void scan_string(const char *str, yyscan_t scanner);

#ifdef __cplusplus
}
#endif